<?php

namespace Yosimitso\WorkingForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{
     public function getThread($start = 0, $limit = 10)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
                ->select('a')
                ->addSelect('b')
                 ->from($this->_entityName,'a')
                ->join('YosimitsoWorkingForumBundle:Post','b','WITH','a.id = b.threadId')
                ->orderBy('a.note','desc')
                ->setMaxResults($limit)
                ->getQuery();
        $query = $queryBuilder->getScalarResult();

        return $query;
    }
    
    public function search($start, $limit = 100,$keywords)
    {
        $keywords = explode(' ',$keywords);
        $where = '';
          foreach ($keywords as $word)
        {
            $where  .= "(a.label LIKE '%".$word."%' OR a.subLabel LIKE '%".$word."%') ";
           
        }         
        
      
         $queryBuilder = $this->_em->createQueryBuilder()
                ->select('a')
                 ->from($this->_entityName,'a')
                 ->where($where)
                 ->setMaxResults($limit)
                 ->getQuery();
                 
             /*   var_dump($queryBuilder);
                 exit();*/
          $query = $queryBuilder->getResult();
        return $query;
    }
}
