require('../scss/forum.scss')
// require('../images/avatar/default.png')
// require('../images/exclamation.png')
// require('../images/lock.png')
// require('../images/lock-btn.png')
// require('../images/moderate.png')
// require('../images/pin.png')
// require('../images/pin2.png')
// require('../images/pin-btn.png')
// require('../images/quote.png')
// require('../images/remove.png')
// require('../images/remove-btn.png')
// require('../images/reply.png')
// require('../images/search.png')
// require('../images/shattered.png')
// require('../images/thumbup.png')
// require('../images/thumbup-has.png')
// require('../images/tick.png')